#!/usr/bin/env python3
"""External-command adapter for the DeepQuantreg package.

The DAQRNN pipeline calls this script through ``DEEPQUANTREG_CMD``. It reads an
input ``.npz`` generated by ``common.baselines.run_deepquantreg_adapter`` and
writes an output ``.npz`` containing ``pred`` with shape ``(n_test, n_taus)``.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import pandas as pd


def _import_deepquantreg():
    try:
        from DeepQuantreg import deep_quantreg as dq
        from DeepQuantreg import utils
    except Exception as exc:  # pragma: no cover - depends on external package
        raise RuntimeError(
            "Cannot import DeepQuantreg. Install it first, for example: "
            "python3 -m pip install git+https://github.com/yicjia/DeepQuantreg.git"
        ) from exc
    return dq, utils


def _patch_deepquantreg_compatibility(dq, utils) -> None:
    """Patch DeepQuantreg for Keras 3 and fragile internal CI diagnostics.

    The published DeepQuantreg package calls ``K.function([model.input], ...)``
    inside ``predict_with_uncertainty``. With recent Keras versions a
    Sequential model created with ``input_dim`` may not expose ``model.input``
    until it has been explicitly called, which raises:

        AttributeError: The layer sequential has never been called ...

    Section 5.4.3 only needs DeepQuantreg point predictions. This replacement
    uses ``model.predict`` and returns the same three-value tuple expected by
    DeepQuantreg's ``deep_quantreg`` function; the lower/upper entries are
    placeholders and are intentionally ignored by our adapter.

    Some versions also call ``lifelines.concordance_index`` through
    ``get_ci``. Simulated test frames can contain no admissible comparable
    pairs, which raises ``ZeroDivisionError`` even though the predictions were
    computed successfully. The adapter evaluates coverage outside the package,
    so the package's internal CI diagnostic is safely replaced by ``nan``.
    """

    def predict_with_uncertainty_keras3(model, X_test):
        X_arr = np.asarray(X_test, dtype=np.float32)
        if X_arr.ndim == 1:
            X_arr = X_arr.reshape(-1, 1)
        try:
            pred = model.predict(X_arr, verbose=0)
        except Exception:
            # Build/call the Sequential model once, then retry prediction.
            model(X_arr[:1])
            pred = model.predict(X_arr, verbose=0)
        pred = np.asarray(pred, dtype=float).reshape(-1)
        return pred, pred.copy(), pred.copy()

    if hasattr(dq, "predict_with_uncertainty"):
        dq.predict_with_uncertainty = predict_with_uncertainty_keras3

    def safe_get_ci(*_args, **_kwargs):
        return float("nan")

    if hasattr(utils, "get_ci"):
        utils.get_ci = safe_get_ci
    if hasattr(dq, "get_ci"):
        dq.get_ci = safe_get_ci


def _right_censoring_frame(X: np.ndarray, y_obs: np.ndarray, delta: np.ndarray, shift: float) -> pd.DataFrame:
    if not np.all(np.isin(delta, [0, 2])):
        raise ValueError("DeepQuantreg adapter only supports right-censored data, delta in {0, 2}.")
    frame = pd.DataFrame(X, columns=[f"x{j + 1}" for j in range(X.shape[1])])
    frame.insert(0, "ind", (delta == 0).astype(int))
    frame.insert(0, "OT", y_obs + shift)
    return frame


def _test_frame(X_test: np.ndarray, dummy_time: float) -> pd.DataFrame:
    frame = pd.DataFrame(X_test, columns=[f"x{j + 1}" for j in range(X_test.shape[1])])
    frame.insert(0, "ind", 1)
    frame.insert(0, "OT", dummy_time)
    return frame


def _as_prediction(result) -> np.ndarray:
    for name in ("predQ", "pred", "prediction", "pred_q"):
        if hasattr(result, name):
            return np.asarray(getattr(result, name), dtype=float).reshape(-1)
    if isinstance(result, dict):
        for name in ("predQ", "pred", "prediction", "pred_q"):
            if name in result:
                return np.asarray(result[name], dtype=float).reshape(-1)
    return np.asarray(result, dtype=float).reshape(-1)


def _complete_data_quantile_prediction(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    tau: float,
    args: argparse.Namespace,
    seed: int,
) -> np.ndarray:
    """Fit the complete-data DeepQuantreg* counterpart.

    The DeepQuantreg package estimates IPCW weights and expects at least one
    censored observation. For the fully observed benchmark there is no
    censoring distribution to estimate, so the method reduces to the same deep
    quantile network trained with the ordinary check loss.
    """

    try:
        import tensorflow as tf
        from tensorflow import keras
    except Exception as exc:  # pragma: no cover - depends on external package
        raise RuntimeError("TensorFlow is required for fully observed DeepQuantreg*.") from exc

    tf.keras.utils.set_random_seed(int(seed))
    X_train = np.asarray(X_train, dtype=np.float32)
    y_train = np.asarray(y_train, dtype=np.float32).reshape(-1, 1)
    X_test = np.asarray(X_test, dtype=np.float32)

    def check_loss(y_true, y_pred):
        err = y_true - y_pred
        return tf.reduce_mean(tf.maximum(float(tau) * err, (float(tau) - 1.0) * err))

    model = keras.Sequential()
    model.add(keras.layers.Input(shape=(X_train.shape[1],)))
    for _ in range(int(args.layer)):
        model.add(keras.layers.Dense(int(args.node), activation="sigmoid"))
        model.add(keras.layers.Dropout(0.2))
    model.add(keras.layers.Dense(1))
    model.compile(optimizer=keras.optimizers.Adam(), loss=check_loss)
    model.fit(
        X_train,
        y_train,
        epochs=int(args.epochs),
        batch_size=int(args.batch_size),
        verbose=0,
    )
    return np.asarray(model.predict(X_test, verbose=0), dtype=float).reshape(-1)


def _tensorflow_runtime_info() -> dict[str, object]:
    """Return lightweight TensorFlow/GPU diagnostics for this subprocess."""

    try:
        import tensorflow as tf
    except Exception as exc:  # pragma: no cover - depends on external package
        return {"available": False, "error": repr(exc)}

    def _device_names(devices):
        return [getattr(device, "name", str(device)) for device in devices]

    try:
        built_with_cuda = bool(tf.test.is_built_with_cuda())
    except Exception:
        built_with_cuda = None

    try:
        physical_gpus = _device_names(tf.config.list_physical_devices("GPU"))
    except Exception:
        physical_gpus = []

    try:
        logical_gpus = _device_names(tf.config.list_logical_devices("GPU"))
    except Exception:
        logical_gpus = []

    return {
        "available": True,
        "version": getattr(tf, "__version__", None),
        "built_with_cuda": built_with_cuda,
        "physical_gpus": physical_gpus,
        "logical_gpus": logical_gpus,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--layer", type=int, default=2)
    parser.add_argument("--node", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--seed", type=int, default=20260430)
    parser.add_argument("--trt", default=None, help="Optional treatment column for DeepQuantreg utils.organize_data.")
    parser.add_argument("input_npz")
    parser.add_argument("output_npz")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    data = np.load(args.input_npz)
    X_train = np.asarray(data["X_train"], dtype=float)
    y_obs = np.asarray(data["y_obs"], dtype=float)
    delta = np.asarray(data["delta"], dtype=int)
    X_test = np.asarray(data["X_test"], dtype=float)
    taus = np.asarray(data["taus"], dtype=float)

    min_time = float(np.nanmin(y_obs))
    shift = 0.0 if min_time > 0.0 else -min_time + 1e-3
    fully_observed = bool(np.all(delta == 0))

    runtime_info = {
        "epochs": int(args.epochs),
        "layer": int(args.layer),
        "node": int(args.node),
        "batch_size": int(args.batch_size),
        "n_train": int(X_train.shape[0]),
        "n_test": int(X_test.shape[0]),
        "n_taus": int(len(taus)),
        "tensorflow": _tensorflow_runtime_info(),
        "mode": "complete_data_quantile_net" if fully_observed else "deepquantreg_ipcw",
        "per_tau_seconds": [],
    }

    if not fully_observed:
        dq, utils = _import_deepquantreg()
        _patch_deepquantreg_compatibility(dq, utils)
        train_df = _right_censoring_frame(X_train, y_obs, delta, shift)
        test_df = _test_frame(X_test, dummy_time=float(np.nanmedian(y_obs + shift)))
        try:
            train_ready = utils.organize_data(train_df, time="OT", event="ind", trt=args.trt)
            test_ready = utils.organize_data(test_df, time="OT", event="ind", trt=args.trt)
        except TypeError:
            train_ready = utils.organize_data(train_df, time="OT", event="ind")
            test_ready = utils.organize_data(test_df, time="OT", event="ind")

    preds = np.empty((X_test.shape[0], len(taus)), dtype=float)
    for j, tau in enumerate(taus):
        t0 = time.perf_counter()
        seed = int(rng.integers(0, 2**31 - 1))
        np.random.seed(seed)
        if fully_observed:
            pred = _complete_data_quantile_prediction(
                X_train,
                y_obs + shift,
                X_test,
                float(tau),
                args,
                seed,
            ) - shift
        else:
            result = dq.deep_quantreg(
                train_ready,
                test_ready,
                layer=int(args.layer),
                node=int(args.node),
                n_epoch=int(args.epochs),
                bsize=int(args.batch_size),
                tau=float(tau),
            )
            pred = _as_prediction(result) - shift
        if pred.shape[0] != X_test.shape[0]:
            raise ValueError(f"DeepQuantreg returned {pred.shape[0]} predictions for {X_test.shape[0]} test rows.")
        preds[:, j] = pred
        runtime_info["per_tau_seconds"].append({"tau": float(tau), "seconds": time.perf_counter() - t0})

    Path(args.output_npz).parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        args.output_npz,
        pred=preds,
        epochs=np.array(int(args.epochs)),
        layer=np.array(int(args.layer)),
        node=np.array(int(args.node)),
        batch_size=np.array(int(args.batch_size)),
        taus=taus,
    )
    runtime_info["total_seconds"] = float(sum(item["seconds"] for item in runtime_info["per_tau_seconds"]))
    runtime_path = Path(args.output_npz).with_name("deepquantreg_runtime.json")
    runtime_path.write_text(json.dumps(runtime_info, indent=2, ensure_ascii=False), encoding="utf-8")


if __name__ == "__main__":
    main()
